---
title: "Data Cleaning - Main"
author: "Ria Rhodes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

# Official state + DC FIPS table
fips_states <- tibble(
  fips = c(
    "01","02","04","05","06","08","09","10","11","12","13","15","16","17","18",
    "19","20","21","22","23","24","25","26","27","28","29","30","31","32","33",
    "34","35","36","37","38","39","40","41","42","44","45","46","47","48","49",
    "50","51","53","54","55","56"
  ),
  state = c(
    "Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut",
    "Delaware","District of Columbia","Florida","Georgia","Hawaii","Idaho","Illinois",
    "Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts",
    "Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada",
    "New Hampshire","New Jersey","New Mexico","New York","North Carolina","North Dakota",
    "Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina",
    "South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington",
    "West Virginia","Wisconsin","Wyoming"
  )
)

```

```{r}
df <- read_csv("main.csv", na = c("N/A", "-", ""))

df_clean <- df %>%
  mutate(
    fips = substr(`Series ID`, 6, 7),
    month = as.integer(substr(Period, 2, 3)),
    Value = as.numeric(Value),
    `1-Month Net Change` = as.numeric(`1-Month Net Change`),
    `1-Month % Change` = as.numeric(`1-Month % Change`)
  ) %>%
  left_join(fips_states, by = "fips") %>%
  relocate(state, .before = Year)

head(df_clean)
```

```{r}
state_avg <- df_clean %>%
  group_by(state) %>%
  summarize(avg_pct_change = mean(`1-Month % Change`, na.rm = TRUE))
```

```{r}
head(state_avg)
```

```{r}
write.csv(df_clean, "clean.csv", row.names = FALSE)
```





